---
version: "2.1"
services:
  sealab-postgres-test:
    image: postgres:9.6
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres